<a href="https://colab.research.google.com/github/UW-CTRL/AA548-spr23/blob/main/demos/svd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Singular Value Decomposition

adapted from https://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm

In [ ]:
A = np.matrix([[2., 4.],
               [1., 3.],
               [0., 0.],
               [0., 0.],
])

Can compute SVD directly using `np.linalg.svd`

In [ ]:
np.linalg.svd?

In [ ]:
u, s, vh = np.linalg.svd(A)

In [ ]:
u, s, vh

(matrix([[-0.81741556, -0.57604844,  0.        ,  0.        ],
         [-0.57604844,  0.81741556,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  1.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([5.4649857 , 0.36596619]),
 matrix([[-0.40455358, -0.9145143 ],
         [-0.9145143 ,  0.40455358]]))

But we also know that:

1. $ (AA^*)x = \sigma^2x$

2. $ (A^*A)y = \sigma^2y$


##  1. $ (AA^*)x = \sigma^2x$

In [ ]:
np.linalg.eig?

In [ ]:
wx, vx = np.linalg.eig(A @ A.T)

In [ ]:
wx, vx

(array([29.86606875,  0.13393125,  0.        ,  0.        ]),
 matrix([[ 0.81741556, -0.57604844,  0.        ,  0.        ],
         [ 0.57604844,  0.81741556,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  1.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [ ]:
np.sqrt(wx)

array([5.4649857 , 0.36596619, 0.        , 0.        ])

## 2. $ (A^*A)y = \sigma^2y$

In [ ]:
wy, vy = np.linalg.eig(A.T @ A)

In [ ]:
wy, vy

(array([ 0.13393125, 29.86606875]), matrix([[-0.9145143 , -0.40455358],
         [ 0.40455358, -0.9145143 ]]))

In [ ]:
np.sqrt(wy)

array([0.36596619, 5.4649857 ])

In [ ]:
vy

matrix([[-0.9145143 , -0.40455358],
        [ 0.40455358, -0.9145143 ]])

In [ ]:
v_ordered = np.concatenate([vy[:,1], vy[:,0]],1)
v_ordered

matrix([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]])

In [ ]:
v_ordered.T

matrix([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]])

In [ ]:
vh

matrix([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]])

In [ ]:
vx

matrix([[ 0.81741556, -0.57604844,  0.        ,  0.        ],
        [ 0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
u

matrix([[-0.81741556, -0.57604844,  0.        ,  0.        ],
        [-0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])